//
//  UIFont+Enum.swift
//  MyApp
//
//  Created by 박권용 on 2022/11/18.
//

import Foundation

enum FontStyle {
  case AcademyEngravedLetPlain
  case AlNile
  case AlNileBold
  case AmericanTypewriter
  case AmericanTypewriterLight
  case AmericanTypewriterSemibold
  case AmericanTypewriterBold
  case AmericanTypewriterCondensed
  case AmericanTypewriterCondensedLight
  case AmericanTypewriterCondensedBold
  case AppleColorEmoji
  case AppleSDGothicNeoRegular
  case AppleSDGothicNeoThin
  case AppleSDGothicNeoUltraLight
  case AppleSDGothicNeoLight
  case AppleSDGothicNeoMedium
  case AppleSDGothicNeoSemiBold
  case AppleSDGothicNeoBold
  case AppleSymbols
  case ArialMT
  case ArialItalicMT
  case ArialBoldMT
  case ArialBoldItalicMT
  case ArialHebrew
  case ArialHebrewLight
  case ArialHebrewBold
  case ArialRoundedMTBold
  case AvenirBook
  case AvenirRoman
  case AvenirBookOblique
  case AvenirOblique
  case AvenirLight
  case AvenirLightOblique
  case AvenirMedium
  case AvenirMediumOblique
  case AvenirHeavy
  case AvenirHeavyOblique
  case AvenirBlack
  case AvenirBlackOblique
  case AvenirNextRegular
  case AvenirNextItalic
  case AvenirNextUltraLight
  case AvenirNextUltraLightItalic
  case AvenirNextMedium
  case AvenirNextMediumItalic
  case AvenirNextDemiBold
  case AvenirNextDemiBoldItalic
  case AvenirNextBold
  case AvenirNextBoldItalic
  case AvenirNextHeavy
  case AvenirNextHeavyItalic
  case AvenirNextCondensedRegular
  case AvenirNextCondensedItalic
  case AvenirNextCondensedUltraLight
  case AvenirNextCondensedUltraLightItalic
  case AvenirNextCondensedMedium
  case AvenirNextCondensedMediumItalic
  case AvenirNextCondensedDemiBold
  case AvenirNextCondensedDemiBoldItalic
  case AvenirNextCondensedBold
  case AvenirNextCondensedBoldItalic
  case AvenirNextCondensedHeavy
  case AvenirNextCondensedHeavyItalic
  case Baskerville
  case BaskervilleItalic
  case BaskervilleSemiBold
  case BaskervilleSemiBoldItalic
  case BaskervilleBold
  case BaskervilleBoldItalic
  case BodoniSvtyTwoITCTTBook
  case BodoniSvtyTwoITCTTBookIta
  case BodoniSvtyTwoITCTTBold
  case BodoniSvtyTwoOSITCTTBook
  case BodoniSvtyTwoOSITCTTBookIt
  case BodoniSvtyTwoOSITCTTBold
  case BodoniSvtyTwoSCITCTTBook
  case BodoniOrnamentsITCTT
  case BradleyHandITCTTBold
  case ChalkboardSERegular
  case ChalkboardSELight
  case ChalkboardSEBold
  case Chalkduster
  case CharterRoman
  case CharterItalic
  case CharterBold
  case CharterBoldItalic
  case CharterBlack
  case CharterBlackItalic
  case Cochin
  case CochinItalic
  case CochinBold
  case CochinBoldItalic
  case Copperplate
  case CopperplateLight
  case CopperplateBold
  case CourierNewPSMT
  case CourierNewPSItalicMT
  case CourierNewPSBoldMT
  case CourierNewPSBoldItalicMT
  case DINAlternateBold
  case DINCondensedBold
  case Damascus
  case DamascusLight
  case DamascusMedium
  case DamascusSemiBold
  case DamascusBold
  case DevanagariSangamMN
  case DevanagariSangamMNBold
  case Didot
  case DidotItalic
  case DidotBold
  case EuphemiaUCAS
  case EuphemiaUCASItalic
  case EuphemiaUCASBold
  case Farah
  case FuturaMedium
  case FuturaMediumItalic
  case FuturaBold
  case FuturaCondensedMedium
  case FuturaCondensedExtraBold
  case Galvji
  case GalvjiBold
  case GeezaPro
  case GeezaProBold
  case Georgia
  case GeorgiaItalic
  case GeorgiaBold
  case GeorgiaBoldItalic
  case GillSans
  case GillSansItalic
  case GillSansLight
  case GillSansLightItalic
  case GillSansSemiBold
  case GillSansSemiBoldItalic
  case GillSansBold
  case GillSansBoldItalic
  case GillSansUltraBold
  case GranthaSangamMNRegular
  case GranthaSangamMNBold
  case Helvetica
  case HelveticaOblique
  case HelveticaLight
  case HelveticaLightOblique
  case HelveticaBold
  case HelveticaBoldOblique
  case HelveticaNeue
  case HelveticaNeueItalic
  case HelveticaNeueUltraLight
  case HelveticaNeueUltraLightItalic
  case HelveticaNeueThin
  case HelveticaNeueThinItalic
  case HelveticaNeueLight
  case HelveticaNeueLightItalic
  case HelveticaNeueMedium
  case HelveticaNeueMediumItalic
  case HelveticaNeueBold
  case HelveticaNeueBoldItalic
  case HelveticaNeueCondensedBold
  case HelveticaNeueCondensedBlack
  case HiraMaruProNW4
  case HiraMinProNW3
  case HiraMinProNW6
  case HiraginoSansW3
  case HiraginoSansW6
  case HiraginoSansW7
  case HoeflerTextRegular
  case HoeflerTextItalic
  case HoeflerTextBlack
  case HoeflerTextBlackItalic
  case Kailasa
  case KailasaBold
  case KefaRegular
  case KhmerSangamMN
  case KohinoorBanglaRegular
  case KohinoorBanglaLight
  case KohinoorBanglaSemibold
  case KohinoorDevanagariRegular
  case KohinoorDevanagariLight
  case KohinoorDevanagariSemibold
  case KohinoorGujaratiRegular
  case KohinoorGujaratiLight
  case KohinoorGujaratiBold
  case KohinoorTeluguRegular
  case KohinoorTeluguLight
  case KohinoorTeluguMedium
  case LaoSangamMN
  case MalayalamSangamMN
  case MalayalamSangamMNBold
  case MarkerFeltThin
  case MarkerFeltWide
  case MenloRegular
  case MenloItalic
  case MenloBold
  case MenloBoldItalic
  case DiwanMishafi
  case MuktaMaheeRegular
  case MuktaMaheeLight
  case MuktaMaheeBold
  case MyanmarSangamMN
  case MyanmarSangamMNBold
  case NoteworthyLight
  case NoteworthyBold
  case NotoNastaliqUrdu
  case NotoNastaliqUrduBold
  case NotoSansKannadaRegular
  case NotoSansKannadaLight
  case NotoSansKannadaBold
  case NotoSansMyanmarRegular
  case NotoSansMyanmarLight
  case NotoSansMyanmarBold
  case NotoSansOriya
  case NotoSansOriyaBold
  case OptimaRegular
  case OptimaItalic
  case OptimaBold
  case OptimaBoldItalic
  case OptimaExtraBlack
  case PalatinoRoman
  case PalatinoItalic
  case PalatinoBold
  case PalatinoBoldItalic
  case Papyrus
  case PapyrusCondensed
  case PartyLetPlain
  case PingFangHKRegular
  case PingFangHKUltralight
  case PingFangHKThin
  case PingFangHKLight
  case PingFangHKMedium
  case PingFangHKSemibold
  case PingFangSCRegular
  case PingFangSCUltralight
  case PingFangSCThin
  case PingFangSCLight
  case PingFangSCMedium
  case PingFangSCSemibold
  case PingFangTCRegular
  case PingFangTCUltralight
  case PingFangTCThin
  case PingFangTCLight
  case PingFangTCMedium
  case PingFangTCSemibold
  case RockwellRegular
  case RockwellItalic
  case RockwellBold
  case RockwellBoldItalic
  case SavoyeLetPlain
  case SinhalaSangamMN
  case SinhalaSangamMNBold
  case SnellRoundhand
  case SnellRoundhandBold
  case SnellRoundhandBlack
  case Symbol
  case TamilSangamMN
  case TamilSangamMNBold
  case Thonburi
  case ThonburiLight
  case ThonburiBold
  case TimesNewRomanPSMT
  case TimesNewRomanPSItalicMT
  case TimesNewRomanPSBoldMT
  case TimesNewRomanPSBoldItalicMT
  case TrebuchetMS
  case TrebuchetMSItalic
  case TrebuchetMSBold
  case TrebuchetBoldItalic
  case Verdana
  case VerdanaItalic
  case VerdanaBold
  case VerdanaBoldItalic
  case ZapfDingbatsITC
  case Zapfino
  
  case JetBrainsMonoRegular
  case JetBrainsMonoMedium
  
  var name: String {
    switch self {
    case .AcademyEngravedLetPlain:
      return "AcademyEngravedLetPlain"
    case .AlNile:
      return "AlNile"
    case .AlNileBold:
      return "AlNile-Bold"
    case .AmericanTypewriter:
      return "AmericanTypewriter"
    case .AmericanTypewriterLight:
      return "AmericanTypewriter-Light"
    case .AmericanTypewriterSemibold:
      return "AmericanTypewriter-Semibold"
    case .AmericanTypewriterBold:
      return "AmericanTypewriter-Bold"
    case .AmericanTypewriterCondensed:
      return "AmericanTypewriter-Condensed"
    case .AmericanTypewriterCondensedLight:
      return "AmericanTypewriter-CondensedLight"
    case .AmericanTypewriterCondensedBold:
      return "AmericanTypewriter-CondensedBold"
    case .AppleColorEmoji:
      return "AppleColorEmoji"
    case .AppleSDGothicNeoRegular:
      return "AppleSDGothicNeo-Regular"
    case .AppleSDGothicNeoThin:
      return "AppleSDGothicNeo-Thin"
    case .AppleSDGothicNeoUltraLight:
      return "AppleSDGothicNeo-UltraLight"
    case .AppleSDGothicNeoLight:
      return "AppleSDGothicNeo-Light"
    case .AppleSDGothicNeoMedium:
      return "AppleSDGothicNeo-Medium"
    case .AppleSDGothicNeoSemiBold:
      return "AppleSDGothicNeo-SemiBold"
    case .AppleSDGothicNeoBold:
      return "AppleSDGothicNeo-Bold"
    case .AppleSymbols:
      return "AppleSymbols"
    case .ArialMT:
      return "ArialMT"
    case .ArialItalicMT:
      return "Arial-ItalicMT"
    case .ArialBoldMT:
      return "Arial-BoldMT"
    case .ArialBoldItalicMT:
      return "Arial-BoldItalicMT"
    case .ArialHebrew:
      return "ArialHebrew"
    case .ArialHebrewLight:
      return "ArialHebrew-Light"
    case .ArialHebrewBold:
      return "ArialHebrew-Bold"
    case .ArialRoundedMTBold:
      return "ArialRoundedMTBold"
    case .AvenirBook:
      return "Avenir-Book"
    case .AvenirRoman:
      return "Avenir-Roman"
    case .AvenirBookOblique:
      return "Avenir-BookOblique"
    case .AvenirOblique:
      return "Avenir-Oblique"
    case .AvenirLight:
      return "Avenir-Light"
    case .AvenirLightOblique:
      return "Avenir-LightOblique"
    case .AvenirMedium:
      return "Avenir-Medium"
    case .AvenirMediumOblique:
      return "Avenir-MediumOblique"
    case .AvenirHeavy:
      return "Avenir-Heavy"
    case .AvenirHeavyOblique:
      return "Avenir-HeavyOblique"
    case .AvenirBlack:
      return "Avenir-Black"
    case .AvenirBlackOblique:
      return "Avenir-BlackOblique"
    case .AvenirNextRegular:
      return "AvenirNext-Regular"
    case .AvenirNextItalic:
      return "AvenirNext-Italic"
    case .AvenirNextUltraLight:
      return "AvenirNext-UltraLight"
    case .AvenirNextUltraLightItalic:
      return "AvenirNext-UltraLightItalic"
    case .AvenirNextMedium:
      return "AvenirNext-Medium"
    case .AvenirNextMediumItalic:
      return "AvenirNext-MediumItalic"
    case .AvenirNextDemiBold:
      return "AvenirNext-DemiBold"
    case .AvenirNextDemiBoldItalic:
      return "AvenirNext-DemiBoldItalic"
    case .AvenirNextBold:
      return "AvenirNext-Bold"
    case .AvenirNextBoldItalic:
      return "AvenirNext-BoldItalic"
    case .AvenirNextHeavy:
      return "AvenirNext-Heavy"
    case .AvenirNextHeavyItalic:
      return "AvenirNext-HeavyItalic"
    case .AvenirNextCondensedRegular:
      return "AvenirNextCondensed-Regular"
    case .AvenirNextCondensedItalic:
      return "AvenirNextCondensed-Italic"
    case .AvenirNextCondensedUltraLight:
      return "AvenirNextCondensed-UltraLight"
    case .AvenirNextCondensedUltraLightItalic:
      return "AvenirNextCondensed-UltraLightItalic"
    case .AvenirNextCondensedMedium:
      return "AvenirNextCondensed-Medium"
    case .AvenirNextCondensedMediumItalic:
      return "AvenirNextCondensed-MediumItalic"
    case .AvenirNextCondensedDemiBold:
      return "AvenirNextCondensed-DemiBold"
    case .AvenirNextCondensedDemiBoldItalic:
      return "AvenirNextCondensed-DemiBoldItalic"
    case .AvenirNextCondensedBold:
      return "AvenirNextCondensed-Bold"
    case .AvenirNextCondensedBoldItalic:
      return "AvenirNextCondensed-BoldItalic"
    case .AvenirNextCondensedHeavy:
      return "AvenirNextCondensed-Heavy"
    case .AvenirNextCondensedHeavyItalic:
      return "AvenirNextCondensed-HeavyItalic"
    case .Baskerville:
      return "Baskerville"
    case .BaskervilleItalic:
      return "Baskerville-Italic"
    case .BaskervilleSemiBold:
      return "Baskerville-SemiBold"
    case .BaskervilleSemiBoldItalic:
      return "Baskerville-SemiBoldItalic"
    case .BaskervilleBold:
      return "Baskerville-Bold"
    case .BaskervilleBoldItalic:
      return "Baskerville-BoldItalic"
    case .BodoniSvtyTwoITCTTBook:
      return "BodoniSvtyTwoITCTT-Book"
    case .BodoniSvtyTwoITCTTBookIta:
      return "BodoniSvtyTwoITCTT-BookIta"
    case .BodoniSvtyTwoITCTTBold:
      return "BodoniSvtyTwoITCTT-Bold"
    case .BodoniSvtyTwoOSITCTTBook:
      return "BodoniSvtyTwoOSITCTT-Book"
    case .BodoniSvtyTwoOSITCTTBookIt:
      return "BodoniSvtyTwoOSITCTT-BookIt"
    case .BodoniSvtyTwoOSITCTTBold:
      return "BodoniSvtyTwoOSITCTT-Bold"
    case .BodoniSvtyTwoSCITCTTBook:
      return "BodoniSvtyTwoSCITCTT-Book"
    case .BodoniOrnamentsITCTT:
      return "BodoniOrnamentsITCTT"
    case .BradleyHandITCTTBold:
      return "BradleyHandITCTT-Bold"
    case .ChalkboardSERegular:
      return "ChalkboardSE-Regular"
    case .ChalkboardSELight:
      return "ChalkboardSE-Light"
    case .ChalkboardSEBold:
      return "ChalkboardSE-Bold"
    case .Chalkduster:
      return "Chalkduster"
    case .CharterRoman:
      return "Charter-Roman"
    case .CharterItalic:
      return "Charter-Italic"
    case .CharterBold:
      return "Charter-Bold"
    case .CharterBoldItalic:
      return "Charter-BoldItalic"
    case .CharterBlack:
      return "Charter-Black"
    case .CharterBlackItalic:
      return "Charter-BlackItalic"
    case .Cochin:
      return "Cochin"
    case .CochinItalic:
      return "Cochin-Italic"
    case .CochinBold:
      return "Cochin-Bold"
    case .CochinBoldItalic:
      return "Cochin-BoldItalic"
    case .Copperplate:
      return "Copperplate"
    case .CopperplateLight:
      return "Copperplate-Light"
    case .CopperplateBold:
      return "Copperplate-Bold"
    case .CourierNewPSMT:
      return "CourierNewPSMT"
    case .CourierNewPSItalicMT:
      return "CourierNewPS-ItalicMT"
    case .CourierNewPSBoldMT:
      return "CourierNewPS-BoldMT"
    case .CourierNewPSBoldItalicMT:
      return "CourierNewPS-BoldItalicMT"
    case .DINAlternateBold:
      return "DINAlternate-Bold"
    case .DINCondensedBold:
      return "DINCondensed-Bold"
    case .Damascus:
      return "Damascus"
    case .DamascusLight:
      return "DamascusLight"
    case .DamascusMedium:
      return "DamascusMedium"
    case .DamascusSemiBold:
      return "DamascusSemiBold"
    case .DamascusBold:
      return "DamascusBold"
    case .DevanagariSangamMN:
      return "DevanagariSangamMN"
    case .DevanagariSangamMNBold:
      return "DevanagariSangamMN-Bold"
    case .Didot:
      return "Didot"
    case .DidotItalic:
      return "Didot-Italic"
    case .DidotBold:
      return "Didot-Bold"
    case .EuphemiaUCAS:
      return "EuphemiaUCAS"
    case .EuphemiaUCASItalic:
      return "EuphemiaUCAS-Italic"
    case .EuphemiaUCASBold:
      return "EuphemiaUCAS-Bold"
    case .Farah:
      return "Farah"
    case .FuturaMedium:
      return "Futura-Medium"
    case .FuturaMediumItalic:
      return "Futura-MediumItalic"
    case .FuturaBold:
      return "Futura-Bold"
    case .FuturaCondensedMedium:
      return "Futura-CondensedMedium"
    case .FuturaCondensedExtraBold:
      return "Futura-CondensedExtraBold"
    case .Galvji:
      return "Galvji"
    case .GalvjiBold:
      return "Galvji-Bold"
    case .GeezaPro:
      return "GeezaPro"
    case .GeezaProBold:
      return "GeezaPro-Bold"
    case .Georgia:
      return "Georgia"
    case .GeorgiaItalic:
      return "Georgia-Italic"
    case .GeorgiaBold:
      return "Georgia-Bold"
    case .GeorgiaBoldItalic:
      return "Georgia-BoldItalic"
    case .GillSans:
      return "GillSans"
    case .GillSansItalic:
      return "GillSans-Italic"
    case .GillSansLight:
      return "GillSans-Light"
    case .GillSansLightItalic:
      return "GillSans-LightItalic"
    case .GillSansSemiBold:
      return "GillSans-SemiBold"
    case .GillSansSemiBoldItalic:
      return "GillSans-SemiBoldItalic"
    case .GillSansBold:
      return "GillSans-Bold"
    case .GillSansBoldItalic:
      return "GillSans-BoldItalic"
    case .GillSansUltraBold:
      return "GillSans-UltraBold"
    case .GranthaSangamMNRegular:
      return "GranthaSangamMN-Regular"
    case .GranthaSangamMNBold:
      return "GranthaSangamMN-Bold"
    case .Helvetica:
      return "Helvetica"
    case .HelveticaOblique:
      return "Helvetica-Oblique"
    case .HelveticaLight:
      return "Helvetica-Light"
    case .HelveticaLightOblique:
      return "Helvetica-LightOblique"
    case .HelveticaBold:
      return "Helvetica-Bold"
    case .HelveticaBoldOblique:
      return "Helvetica-BoldOblique"
    case .HelveticaNeue:
      return "HelveticaNeue"
    case .HelveticaNeueItalic:
      return "HelveticaNeue-Italic"
    case .HelveticaNeueUltraLight:
      return "HelveticaNeue-UltraLight"
    case .HelveticaNeueUltraLightItalic:
      return "HelveticaNeue-UltraLightItalic"
    case .HelveticaNeueThin:
      return "HelveticaNeue-Thin"
    case .HelveticaNeueThinItalic:
      return "HelveticaNeue-ThinItalic"
    case .HelveticaNeueLight:
      return "HelveticaNeue-Light"
    case .HelveticaNeueLightItalic:
      return "HelveticaNeue-LightItalic"
    case .HelveticaNeueMedium:
      return "HelveticaNeue-Medium"
    case .HelveticaNeueMediumItalic:
      return "HelveticaNeue-MediumItalic"
    case .HelveticaNeueBold:
      return "HelveticaNeue-Bold"
    case .HelveticaNeueBoldItalic:
      return "HelveticaNeue-BoldItalic"
    case .HelveticaNeueCondensedBold:
      return "HelveticaNeue-CondensedBold"
    case .HelveticaNeueCondensedBlack:
      return "HelveticaNeue-CondensedBlack"
    case .HiraMaruProNW4:
      return "HiraMaruProN-W4"
    case .HiraMinProNW3:
      return "HiraMinProN-W3"
    case .HiraMinProNW6:
      return "HiraMinProN-W6"
    case .HiraginoSansW3:
      return "HiraginoSans-W3"
    case .HiraginoSansW6:
      return "HiraginoSans-W6"
    case .HiraginoSansW7:
      return "HiraginoSans-W7"
    case .HoeflerTextRegular:
      return "HoeflerText-Regular"
    case .HoeflerTextItalic:
      return "HoeflerText-Italic"
    case .HoeflerTextBlack:
      return "HoeflerText-Black"
    case .HoeflerTextBlackItalic:
      return "HoeflerText-BlackItalic"
    case .Kailasa:
      return "Kailasa"
    case .KailasaBold:
      return "Kailasa-Bold"
    case .KefaRegular:
      return "Kefa-Regular"
    case .KhmerSangamMN:
      return "KhmerSangamMN"
    case .KohinoorBanglaRegular:
      return "KohinoorBangla-Regular"
    case .KohinoorBanglaLight:
      return "KohinoorBangla-Light"
    case .KohinoorBanglaSemibold:
      return "KohinoorBangla-Semibold"
    case .KohinoorDevanagariRegular:
      return "KohinoorDevanagari-Regular"
    case .KohinoorDevanagariLight:
      return "KohinoorDevanagari-Light"
    case .KohinoorDevanagariSemibold:
      return "KohinoorDevanagari-Semibold"
    case .KohinoorGujaratiRegular:
      return "KohinoorGujarati-Regular"
    case .KohinoorGujaratiLight:
      return "KohinoorGujarati-Light"
    case .KohinoorGujaratiBold:
      return "KohinoorGujarati-Bold"
    case .KohinoorTeluguRegular:
      return "KohinoorTelugu-Regular"
    case .KohinoorTeluguLight:
      return "KohinoorTelugu-Light"
    case .KohinoorTeluguMedium:
      return "KohinoorTelugu-Medium"
    case .LaoSangamMN:
      return "LaoSangamMN"
    case .MalayalamSangamMN:
      return "MalayalamSangamMN"
    case .MalayalamSangamMNBold:
      return "MalayalamSangamMN-Bold"
    case .MarkerFeltThin:
      return "MarkerFelt-Thin"
    case .MarkerFeltWide:
      return "MarkerFelt-Wide"
    case .MenloRegular:
      return "Menlo-Regular"
    case .MenloItalic:
      return "Menlo-Italic"
    case .MenloBold:
      return "Menlo-Bold"
    case .MenloBoldItalic:
      return "Menlo-BoldItalic"
    case .DiwanMishafi:
      return "DiwanMishafi"
    case .MuktaMaheeRegular:
      return "MuktaMahee-Regular"
    case .MuktaMaheeLight:
      return "MuktaMahee-Light"
    case .MuktaMaheeBold:
      return "MuktaMahee-Bold"
    case .MyanmarSangamMN:
      return "MyanmarSangamMN"
    case .MyanmarSangamMNBold:
      return "MyanmarSangamMN-Bold"
    case .NoteworthyLight:
      return "Noteworthy-Light"
    case .NoteworthyBold:
      return "Noteworthy-Bold"
    case .NotoNastaliqUrdu:
      return "NotoNastaliqUrdu"
    case .NotoNastaliqUrduBold:
      return "NotoNastaliqUrdu-Bold"
    case .NotoSansKannadaRegular:
      return "NotoSansKannada-Regular"
    case .NotoSansKannadaLight:
      return "NotoSansKannada-Light"
    case .NotoSansKannadaBold:
      return "NotoSansKannada-Bold"
    case .NotoSansMyanmarRegular:
      return "NotoSansMyanmar-Regular"
    case .NotoSansMyanmarLight:
      return "NotoSansMyanmar-Light"
    case .NotoSansMyanmarBold:
      return "NotoSansMyanmar-Bold"
    case .NotoSansOriya:
      return "NotoSansOriya"
    case .NotoSansOriyaBold:
      return "NotoSansOriya-Bold"
    case .OptimaRegular:
      return "Optima-Regular"
    case .OptimaItalic:
      return "Optima-Italic"
    case .OptimaBold:
      return "Optima-Bold"
    case .OptimaBoldItalic:
      return "Optima-BoldItalic"
    case .OptimaExtraBlack:
      return "Optima-ExtraBlack"
    case .PalatinoRoman:
      return "Palatino-Roman"
    case .PalatinoItalic:
      return "Palatino-Italic"
    case .PalatinoBold:
      return "Palatino-Bold"
    case .PalatinoBoldItalic:
      return "Palatino-BoldItalic"
    case .Papyrus:
      return "Papyrus"
    case .PapyrusCondensed:
      return "Papyrus-Condensed"
    case .PartyLetPlain:
      return "PartyLetPlain"
    case .PingFangHKRegular:
      return "PingFangHK-Regular"
    case .PingFangHKUltralight:
      return "PingFangHK-Ultralight"
    case .PingFangHKThin:
      return "PingFangHK-Thin"
    case .PingFangHKLight:
      return "PingFangHK-Light"
    case .PingFangHKMedium:
      return "PingFangHK-Medium"
    case .PingFangHKSemibold:
      return "PingFangHK-Semibold"
    case .PingFangSCRegular:
      return "PingFangSC-Regular"
    case .PingFangSCUltralight:
      return "PingFangSC-Ultralight"
    case .PingFangSCThin:
      return "PingFangSC-Thin"
    case .PingFangSCLight:
      return "PingFangSC-Light"
    case .PingFangSCMedium:
      return "PingFangSC-Medium"
    case .PingFangSCSemibold:
      return "PingFangSC-Semibold"
    case .PingFangTCRegular:
      return "PingFangTC-Regular"
    case .PingFangTCUltralight:
      return "PingFangTC-Ultralight"
    case .PingFangTCThin:
      return "PingFangTC-Thin"
    case .PingFangTCLight:
      return "PingFangTC-Light"
    case .PingFangTCMedium:
      return "PingFangTC-Medium"
    case .PingFangTCSemibold:
      return "PingFangTC-Semibold"
    case .RockwellRegular:
      return "Rockwell-Regular"
    case .RockwellItalic:
      return "Rockwell-Italic"
    case .RockwellBold:
      return "Rockwell-Bold"
    case .RockwellBoldItalic:
      return "Rockwell-BoldItalic"
    case .SavoyeLetPlain:
      return "SavoyeLetPlain"
    case .SinhalaSangamMN:
      return "SinhalaSangamMN"
    case .SinhalaSangamMNBold:
      return "SinhalaSangamMN-Bold"
    case .SnellRoundhand:
      return "SnellRoundhand"
    case .SnellRoundhandBold:
      return "SnellRoundhand-Bold"
    case .SnellRoundhandBlack:
      return "SnellRoundhand-Black"
    case .Symbol:
      return "Symbol"
    case .TamilSangamMN:
      return "TamilSangamMN"
    case .TamilSangamMNBold:
      return "TamilSangamMN-Bold"
    case .Thonburi:
      return "Thonburi"
    case .ThonburiLight:
      return "Thonburi-Light"
    case .ThonburiBold:
      return "Thonburi-Bold"
    case .TimesNewRomanPSMT:
      return "TimesNewRomanPSMT"
    case .TimesNewRomanPSItalicMT:
      return "TimesNewRomanPS-ItalicMT"
    case .TimesNewRomanPSBoldMT:
      return "TimesNewRomanPS-BoldMT"
    case .TimesNewRomanPSBoldItalicMT:
      return "TimesNewRomanPS-BoldItalicMT"
    case .TrebuchetMS:
      return "TrebuchetMS"
    case .TrebuchetMSItalic:
      return "TrebuchetMS-Italic"
    case .TrebuchetMSBold:
      return "TrebuchetMS-Bold"
    case .TrebuchetBoldItalic:
      return "Trebuchet-BoldItalic"
    case .Verdana:
      return "Verdana"
    case .VerdanaItalic:
      return "Verdana-Italic"
    case .VerdanaBold:
      return "Verdana-Bold"
    case .VerdanaBoldItalic:
      return "Verdana-BoldItalic"
    case .ZapfDingbatsITC:
      return "ZapfDingbatsITC"
    case .Zapfino:
      return "Zapfino"

    case .JetBrainsMonoRegular:
      return "JetBrainsMono-Regular"
    case .JetBrainsMonoMedium:
      return "JetBrainsMono-Medium"
    }
  }
}
